### ISSUE TITLE
You forgot to import _init_paths

### ISSUE THREAD

**Issue by engineer1109** [auroua/tf_rfcn#3]
import _init_paths
You forgot to copy _init_paths.py and import it.
Everything import model.xxxx can't work

**Comment by engineer1109** [comment]
cfg_from_list(args.set_cfgs)  reports type error

**Comment by engineer1109** [comment]
too chaos ， I want to migrate XinLei's script to your code

**Comment by auroua** [comment]
You can use `sys.path.append('xxx')` to add modules.
